#!/usr/bin/env python3
"""Generate Sources/Render/IconPaths.swift from design/icons/*.svg.

Each icon's inner XML (the <path> elements) is embedded so the renderer can
inline used icons once as <symbol> in <defs>.
"""
import re
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
ICONS = ROOT / "design" / "icons"
OUT = ROOT / "Sources" / "Render" / "IconPaths.swift"


def main():
    entries = []
    for svg in sorted(ICONS.glob("*.svg")):
        inner = re.search(r"<svg[^>]*>(.*)</svg>", svg.read_text(), re.S).group(1).strip()
        inner = inner.replace('"', '\\"')
        entries.append(f'    "{svg.stem}": "{inner}",')
    OUT.write_text(
        "// Generated by scripts/generate-icons.py from design/icons/ — do not edit.\n"
        "import ProfileKit\n\n"
        "/// Inner XML for each icon, keyed by `Icon.rawValue` (16x16 viewBox, Octicons).\n"
        "let iconPaths: [String: String] = [\n" + "\n".join(entries) + "\n]\n"
    )
    print(f"wrote {OUT.relative_to(ROOT)} ({len(entries)} icons)")


if __name__ == "__main__":
    main()
