#!/usr/bin/env python3
"""Generate themes/<name>.<variant>.yml from design/tokens/*.css.

The CSS custom-property files in design/ are the source of truth; this script
translates them once into the YAML files the renderer ships. Variants that only
override some tokens (default-dark) are merged over their light base.
"""
import re
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
TOKENS = ROOT / "design" / "tokens"
THEMES = ROOT / "themes"

# selector in CSS -> (theme name, variant)
VARIANTS = {
    ":root": ("default", "light"),
    "default-dark": ("default", "dark"),
    "paper": ("paper", "light"),
    "paper-dark": ("paper", "dark"),
    "terminal": ("terminal", "dark"),
    "ocean": ("ocean", "light"),
    "ocean-dark": ("ocean", "dark"),
    "marker": ("marker", "light"),
    "marker-dark": ("marker", "dark"),
}

# variants that inherit unspecified tokens from another block
BASES = {("default", "dark"): ("default", "light")}


def parse_blocks(css: str):
    for m in re.finditer(r'(:root|\[data-theme="([^"]+)"\])\s*\{(.*?)\}', css, re.S):
        selector = m.group(2) or ":root"
        props = dict(re.findall(r"--([a-z0-9-]+)\s*:\s*([^;]+);", m.group(3)))
        yield selector, props


def px(value: str) -> str:
    return value.removesuffix("px")


def quote(value: str) -> str:
    return f'"{value}"'


def emit(tokens: dict) -> str:
    t = tokens
    heat = ", ".join(quote(t[f"heat-{i}"]) for i in range(5))
    stack = t["font-stack"].replace('"', '\\"')
    return f"""font:
  stack: "{stack}"
  sizeBase: {px(t['font-size-base'])}
  sizeTitle: {px(t['font-size-title'])}
  sizeSmall: {px(t['font-size-small'])}
card:
  bg: {quote(t['card-bg'])}
  border: {quote(t['card-border'])}
  borderWidth: {px(t['card-border-width'])}
  radius: {px(t['card-radius'])}
  padding: {px(t['card-padding'])}
text:
  primary: {quote(t['text-primary'])}
  muted: {quote(t['text-muted'])}
  accent: {quote(t['accent'])}
heatmap:
  scale: [{heat}]
spark:
  stroke: {quote(t['spark-stroke'])}
  fill: {quote(t['spark-fill'])}
bar:
  track: {quote(t['bar-track'])}
  fill: {quote(t['bar-fill'])}
badge:
  bg: {quote(t['badge-bg'])}
  text: {quote(t['badge-text'])}
"""


def main():
    parsed = {}  # (name, variant) -> tokens
    for css_file in sorted(TOKENS.glob("*.css")):
        for selector, props in parse_blocks(css_file.read_text()):
            name, variant = VARIANTS[selector]
            parsed[(name, variant)] = props

    THEMES.mkdir(exist_ok=True)
    yamls = {}
    for (name, variant), props in sorted(parsed.items()):
        base = BASES.get((name, variant))
        tokens = dict(parsed[base]) if base else {}
        tokens.update(props)
        path = THEMES / f"{name}.{variant}.yml"
        header = f"# Generated from design/tokens/{name}.css — edit there, then re-run scripts/generate-themes.py\n"
        body = emit(tokens)
        path.write_text(header + body)
        yamls[f"{name}.{variant}"] = body
        print(f"wrote {path.relative_to(ROOT)}")

    # Also embed the themes in the binary so the released executable is
    # self-contained (no resource bundle to ship next to it).
    swift_path = ROOT / "Sources" / "Render" / "BundledThemes.swift"
    entries = "\n".join(
        '    "{}": """\n{}""",'.format(key, body.replace("\\", "\\\\"))
        for key, body in sorted(yamls.items())
    )
    swift_path.write_text(
        "// Generated by scripts/generate-themes.py from design/tokens/ — do not edit.\n\n"
        "/// YAML for every shipped theme, keyed \"<name>.<variant>\". Mirrors themes/.\n"
        "public let bundledThemes: [String: String] = [\n"
        f"{entries}\n"
        "]\n"
    )
    print(f"wrote {swift_path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
