// Generated by scripts/generate-themes.py from design/tokens/ — do not edit.

/// YAML for every shipped theme, keyed "<name>.<variant>". Mirrors themes/.
public let bundledThemes: [String: String] = [
    "default.dark": """
font:
  stack: "-apple-system,BlinkMacSystemFont,\\"Segoe UI\\",Roboto,Helvetica,Arial,sans-serif"
  sizeBase: 12
  sizeTitle: 14
  sizeSmall: 11
card:
  bg: "#151b23"
  border: "#2f3742"
  borderWidth: 1
  radius: 6
  padding: 20
text:
  primary: "#e6edf3"
  muted: "#9198a1"
  accent: "#3fb950"
heatmap:
  scale: ["#232b35", "#113a24", "#1a7f37", "#2ea043", "#56d364"]
spark:
  stroke: "#3fb950"
  fill: "#3fb95029"
bar:
  track: "#232b35"
  fill: "#3fb950"
badge:
  bg: "#232b35"
  text: "#9198a1"
""",
    "default.light": """
font:
  stack: "-apple-system,BlinkMacSystemFont,\\"Segoe UI\\",Roboto,Helvetica,Arial,sans-serif"
  sizeBase: 12
  sizeTitle: 14
  sizeSmall: 11
card:
  bg: "#ffffff"
  border: "#d1d9e0"
  borderWidth: 1
  radius: 6
  padding: 20
text:
  primary: "#1f2328"
  muted: "#59636e"
  accent: "#1a7f37"
heatmap:
  scale: ["#eff2f5", "#aceebb", "#4ac26b", "#2da44e", "#116329"]
spark:
  stroke: "#2da44e"
  fill: "#2da44e29"
bar:
  track: "#eff2f5"
  fill: "#2da44e"
badge:
  bg: "#eef1f4"
  text: "#3f4954"
""",
    "marker.dark": """
font:
  stack: "-apple-system,BlinkMacSystemFont,\\"Segoe UI\\",Roboto,Helvetica,Arial,sans-serif"
  sizeBase: 12
  sizeTitle: 14
  sizeSmall: 11
card:
  bg: "#191512"
  border: "#f2e9dc"
  borderWidth: 2
  radius: 14
  padding: 20
text:
  primary: "#f6ede0"
  muted: "#a3958a"
  accent: "#ff7a4d"
heatmap:
  scale: ["#241f1a", "#66301b", "#a84a22", "#e8662f", "#ffa15e"]
spark:
  stroke: "#ff7a4d"
  fill: "#ff7a4d26"
bar:
  track: "#241f1a"
  fill: "#ff7a4d"
badge:
  bg: "#f2e9dc"
  text: "#191512"
""",
    "marker.light": """
font:
  stack: "-apple-system,BlinkMacSystemFont,\\"Segoe UI\\",Roboto,Helvetica,Arial,sans-serif"
  sizeBase: 12
  sizeTitle: 14
  sizeSmall: 11
card:
  bg: "#fffdf4"
  border: "#221d1a"
  borderWidth: 2
  radius: 14
  padding: 20
text:
  primary: "#221d1a"
  muted: "#6f645c"
  accent: "#f4632e"
heatmap:
  scale: ["#f1ece1", "#ffd1a6", "#ff9e5e", "#f4632e", "#a82c0c"]
spark:
  stroke: "#f4632e"
  fill: "#f4632e26"
bar:
  track: "#f1ece1"
  fill: "#f4632e"
badge:
  bg: "#221d1a"
  text: "#fffdf4"
""",
    "ocean.dark": """
font:
  stack: "-apple-system,BlinkMacSystemFont,\\"Segoe UI\\",Roboto,Helvetica,Arial,sans-serif"
  sizeBase: 12
  sizeTitle: 14
  sizeSmall: 11
card:
  bg: "#0f1a22"
  border: "#24384a"
  borderWidth: 1
  radius: 8
  padding: 20
text:
  primary: "#dcebf5"
  muted: "#87a3b8"
  accent: "#3fa9e0"
heatmap:
  scale: ["#182835", "#0d3f5c", "#136a94", "#2b9cd0", "#6cd2ff"]
spark:
  stroke: "#3fa9e0"
  fill: "#3fa9e026"
bar:
  track: "#182835"
  fill: "#3fa9e0"
badge:
  bg: "#182835"
  text: "#87a3b8"
""",
    "ocean.light": """
font:
  stack: "-apple-system,BlinkMacSystemFont,\\"Segoe UI\\",Roboto,Helvetica,Arial,sans-serif"
  sizeBase: 12
  sizeTitle: 14
  sizeSmall: 11
card:
  bg: "#ffffff"
  border: "#cfdce6"
  borderWidth: 1
  radius: 8
  padding: 20
text:
  primary: "#16232e"
  muted: "#5b7183"
  accent: "#0e7bb8"
heatmap:
  scale: ["#e9f0f5", "#a5d8f0", "#4fa8d8", "#1379ae", "#0a4a73"]
spark:
  stroke: "#1379ae"
  fill: "#1379ae24"
bar:
  track: "#e9f0f5"
  fill: "#1379ae"
badge:
  bg: "#e4eef5"
  text: "#446a85"
""",
    "paper.dark": """
font:
  stack: "Georgia,serif"
  sizeBase: 12
  sizeTitle: 14
  sizeSmall: 11
card:
  bg: "#201c14"
  border: "#3d3626"
  borderWidth: 1
  radius: 4
  padding: 22
text:
  primary: "#ece4d2"
  muted: "#a4977c"
  accent: "#e08d52"
heatmap:
  scale: ["#2a251b", "#54401f", "#8a5f2c", "#c07a3e", "#e8ae6c"]
spark:
  stroke: "#e08d52"
  fill: "#e08d5226"
bar:
  track: "#2a251b"
  fill: "#e08d52"
badge:
  bg: "#2e2920"
  text: "#b3a68a"
""",
    "paper.light": """
font:
  stack: "Georgia,serif"
  sizeBase: 12
  sizeTitle: 14
  sizeSmall: 11
card:
  bg: "#f6f1e7"
  border: "#ddd3bf"
  borderWidth: 1
  radius: 4
  padding: 22
text:
  primary: "#26221a"
  muted: "#756952"
  accent: "#b0552a"
heatmap:
  scale: ["#ebe3d2", "#e5c9a1", "#d19a5d", "#b0552a", "#6e3216"]
spark:
  stroke: "#b0552a"
  fill: "#b0552a24"
bar:
  track: "#ebe3d2"
  fill: "#b0552a"
badge:
  bg: "#efe8d9"
  text: "#6b5f47"
""",
    "terminal.dark": """
font:
  stack: "ui-monospace,\\"SF Mono\\",SFMono-Regular,Menlo,Consolas,\\"Liberation Mono\\",monospace"
  sizeBase: 12
  sizeTitle: 13
  sizeSmall: 11
card:
  bg: "#0a0f0a"
  border: "#1e3320"
  borderWidth: 1
  radius: 0
  padding: 18
text:
  primary: "#93f5a3"
  muted: "#4d8a58"
  accent: "#35e65a"
heatmap:
  scale: ["#101810", "#14421e", "#1c6b2c", "#27a53f", "#49f568"]
spark:
  stroke: "#35e65a"
  fill: "#35e65a26"
bar:
  track: "#101810"
  fill: "#35e65a"
badge:
  bg: "#112413"
  text: "#6fce7f"
""",
]
